module.exports = [
  {
    id: 'q01',
    scene: '楼梯间潮热发粘。办成大事，却要踩过一个人——你？',
    bookHint: '《罪与罚》',
    options: [
      {
        text: '先跨过去，事后再解释',
        flash: {
          who: '拉斯柯尔尼科夫',
          characterId: 'raskolnikov',
          line: '楼梯间的空气发粘。他握紧想法——不是为钱，是为证明自己有权跨过去。',
          image: '/assets/scenes/q01-A.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 5, 怜悯: 1, 激情: 3, 虚无: 2, 自尊: 5, 热忱: 2 },
      },
      {
        text: '停手，人不能当垫脚石',
        flash: {
          who: '索尼娅',
          characterId: 'sonya',
          line: '她没有争辩对错。只是伸手，把那个人从黑暗边缘轻轻拉回来。',
          image: '/assets/scenes/q01-B.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 1, 怜悯: 5, 激情: 2, 虚无: 1, 自尊: 2, 热忱: 3 },
      },
      {
        text: '笑着耸肩，认真不起来',
        flash: {
          who: '斯维德里盖洛夫',
          characterId: 'svidrigailov',
          line: '他笑了一下，像在看一场乏味的戏。所谓界限，不过是别人吓自己的词。',
          image: '/assets/scenes/q01-C.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 3, 怜悯: 1, 激情: 3, 虚无: 5, 自尊: 1, 热忱: 1 },
      },
    ],
    quote: '凡是非凡的人，都有权利允许自己的良心跨过某些障碍。',
    quoteSource: '《罪与罚》',
  },
  {
    id: 'q02',
    scene: '腹壁温热发黏。外面在喊救命，你却觉得这里更安全——你？',
    bookHint: '《鳄鱼》',
    options: [
      {
        text: '留下，并证明被吞是福气',
        flash: {
          who: '斯维德里盖洛夫',
          characterId: 'svidrigailov',
          line: '他靠着温热的内壁，竟笑出声：外面那么吵，这里反而清静。',
          image: '/assets/scenes/q02-A.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 3, 怜悯: 1, 激情: 2, 虚无: 5, 自尊: 2, 热忱: 1 },
      },
      {
        text: '拼全力往外撕，哪怕更苦',
        flash: {
          who: '德米特里',
          characterId: 'dmitry-karamazov',
          line: '他用拳头砸向黑暗：关在肚子里苟活，那不叫活着。',
          image: '/assets/scenes/q02-B.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 1, 怜悯: 2, 激情: 5, 虚无: 1, 自尊: 4, 热忱: 5 },
      },
      {
        text: '嘴上说挺好，夜里恨自己',
        flash: {
          who: '地下室人',
          characterId: 'underground-man',
          line: '他对空墙说「挺好」，手却掐进掌心：放弃挣扎的人，最恨自己。',
          image: '/assets/scenes/q02-C.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 4, 怜悯: 1, 激情: 2, 虚无: 4, 自尊: 5, 热忱: 1 },
      },
    ],
    quote: '人可以习惯一切，哪怕是绞刑架。',
    quoteSource: '《死屋手记》',
  },
  {
    id: 'q03',
    scene: '笑声砸过来。大家只要开心果，不要面具后面的你——你？',
    bookHint: '《波尔宗科夫》',
    options: [
      {
        text: '继续演，至少还有位置',
        flash: {
          who: '老卡拉马佐夫',
          characterId: 'fyodor-karamazov',
          line: '他举杯大笑，把真心咽下去：你们要热闹，我就给热闹。',
          image: '/assets/scenes/q03-A.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 3, 怜悯: 2, 激情: 3, 虚无: 5, 自尊: 1, 热忱: 2 },
      },
      {
        text: '撕下面具，让气氛变冷',
        flash: {
          who: '杜尼娅',
          characterId: 'dunya',
          line: '她收住笑，抬起下巴：你们可以不要我，但不能再只看见这张脸。',
          image: '/assets/scenes/q03-B.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 2, 怜悯: 1, 激情: 4, 虚无: 1, 自尊: 5, 热忱: 3 },
      },
      {
        text: '演太久，分不清谁是我',
        flash: {
          who: '戈利亚德金',
          characterId: 'golyadkin-senior',
          line: '镜里那个人还在笑。他伸手去摸脸，却摸到一层摘不下来的皮。',
          image: '/assets/scenes/q03-C.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 3, 怜悯: 1, 激情: 2, 虚无: 5, 自尊: 4, 热忱: 1 },
      },
    ],
    quote: '人们把他当作笑话，他自己却比嘲笑者更清醒。',
    quoteSource: '《波尔宗科夫》',
  },
  {
    id: 'q04',
    scene: '宴席还在算计利益。你偏想做件对自己有害的蠢事——你？',
    bookHint: '《地下室手记》',
    options: [
      {
        text: '故意踩偏，证明我不是琴键',
        flash: {
          who: '地下室人',
          characterId: 'underground-man',
          line: '他明知会疼，仍把杯子碰翻：我宁可痛苦地自由，也不做快乐的奴隶。',
          image: '/assets/scenes/q04-A.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 5, 怜悯: 1, 激情: 3, 虚无: 4, 自尊: 5, 热忱: 1 },
      },
      {
        text: '不干蠢事，用理性护住自己',
        flash: {
          who: '波尔菲里',
          characterId: 'porfiry',
          line: '他轻轻放下刀叉：自由若只会自伤，那不过是换了一种镣铐。',
          image: '/assets/scenes/q04-B.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 5, 怜悯: 2, 激情: 1, 虚无: 1, 自尊: 3, 热忱: 3 },
      },
      {
        text: '想过，却退回潮湿角落怨世界',
        flash: {
          who: '地下室人',
          characterId: 'underground-man',
          line: '他关上门，对着潮湿墙壁骂完所有人，又骂更不敢出门的自己。',
          image: '/assets/scenes/q04-C.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 4, 怜悯: 1, 激情: 2, 虚无: 5, 自尊: 5, 热忱: 1 },
      },
    ],
    quote: '我是有病的人。我太清醒了。',
    quoteSource: '《地下室手记》',
  },
  {
    id: 'q05',
    scene: '老人忽然攥紧你的手：你是不是在骗我？随即又糊涂——你？',
    bookHint: '《舅舅的梦》',
    options: [
      {
        text: '趁清醒，把真相说出口',
        flash: {
          who: '沙托夫',
          characterId: 'shatov',
          line: '他声音发颤，却更定：这一刻可能是最后一次——他有权知道。',
          image: '/assets/scenes/q05-A.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 4, 怜悯: 3, 激情: 2, 虚无: 1, 自尊: 3, 热忱: 5 },
      },
      {
        text: '继续撒谎，护住他最后的幻觉',
        flash: {
          who: '索尼娅',
          characterId: 'sonya',
          line: '她反握住那只手，轻声说：没有骗你。把残酷的真相咽回肚里。',
          image: '/assets/scenes/q05-B.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 2, 怜悯: 5, 激情: 1, 虚无: 1, 自尊: 2, 热忱: 4 },
      },
      {
        text: '犹豫开口，话未出口他又糊涂',
        flash: {
          who: '戈利亚德金',
          characterId: 'golyadkin-senior',
          line: '词语卡在喉口。等他准备好，那双眼睛已经重新失焦。',
          image: '/assets/scenes/q05-C.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 3, 怜悯: 3, 激情: 1, 虚无: 4, 自尊: 3, 热忱: 1 },
      },
    ],
    quote: '你们都在骗我，对不对？',
    quoteSource: '《舅舅的梦》',
  },
  {
    id: 'q06',
    scene: '客厅里人人围着糊涂贵人演戏。茶凉了，你把手往哪放？',
    bookHint: '《舅舅的梦》',
    options: [
      {
        text: '加入演出，顺便捞点好处',
        flash: {
          who: '彼得·韦尔霍文斯基',
          characterId: 'pyotr-verkhovensky',
          line: '他凑近耳边奉承一句，眼睛却在找缺口：不演的人，才是异类。',
          image: '/assets/scenes/q06-A.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 4, 怜悯: 1, 激情: 3, 虚无: 5, 自尊: 2, 热忱: 3 },
      },
      {
        text: '不奉承也不揭穿，冷淡旁观',
        flash: {
          who: '斯塔夫罗金',
          characterId: 'stavrogin',
          line: '他坐在边角喝茶，像接受献祭，却不献出自己。',
          image: '/assets/scenes/q06-B.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 4, 怜悯: 1, 激情: 1, 虚无: 5, 自尊: 3, 热忱: 1 },
      },
      {
        text: '当场撕破这荒诞的笑脸',
        flash: {
          who: '德米特里',
          characterId: 'dmitry-karamazov',
          line: '他把杯子顿在桌上：够了。虚伪的热闹比沉默更脏。',
          image: '/assets/scenes/q06-C.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 1, 怜悯: 2, 激情: 5, 虚无: 1, 自尊: 4, 热忱: 4 },
      },
    ],
    quote: '人人都心知肚明，却仍把这场戏演到底。',
    quoteSource: '《舅舅的梦》',
  },
  {
    id: 'q07',
    scene: '有人真的走近你。你渴望被看见，又怕被看穿——你？',
    bookHint: '《地下室手记》',
    options: [
      {
        text: '推开靠近的人，守住软肋',
        flash: {
          who: '地下室人',
          characterId: 'underground-man',
          line: '他笑着回刺一句：被看穿比被误解更可怕。门在对方面前关上。',
          image: '/assets/scenes/q07-A.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 4, 怜悯: 1, 激情: 2, 虚无: 5, 自尊: 5, 热忱: 1 },
      },
      {
        text: '打开一条缝，让人看见一点',
        flash: {
          who: '阿辽沙',
          characterId: 'alyosha-karamazov',
          line: '他没有一次交完底。只是把椅子拉近一点：也许这次，可以试。',
          image: '/assets/scenes/q07-B.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 2, 怜悯: 5, 激情: 2, 虚无: 1, 自尊: 2, 热忱: 4 },
      },
      {
        text: '推开又拉回，把人搞疯',
        flash: {
          who: '纳斯塔霞',
          characterId: 'nastasya',
          line: '她抓住又松开：来吧——别靠近。渴望与羞耻在同一只手里较劲。',
          image: '/assets/scenes/q07-C.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 2, 怜悯: 2, 激情: 5, 虚无: 3, 自尊: 5, 热忱: 2 },
      },
    ],
    quote: '他渴望被看见，又在被看见的瞬间逃跑。',
    quoteSource: '《地下室手记》',
  },
  {
    id: 'q08',
    scene: '舞会灯下，另一个更会来事的你先寒暄——你？',
    bookHint: '《双重人格》',
    options: [
      {
        text: '越解释越乱，死守体面',
        flash: {
          who: '戈利亚德金',
          characterId: 'golyadkin-senior',
          line: '他连连鞠躬，词语绊在舌头上：我不是那样的人——越说，缝越大。',
          image: '/assets/scenes/q08-A.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 2, 怜悯: 2, 激情: 3, 虚无: 3, 自尊: 5, 热忱: 1 },
      },
      {
        text: '让那个更会处事的自己上场',
        flash: {
          who: '小戈利亚德金',
          characterId: 'golyadkin-junior',
          line: '他笑得恰到好处，抢先握手。场面站在他这边，本人却被挤到阴影里。',
          image: '/assets/scenes/q08-B.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 4, 怜悯: 1, 激情: 3, 虚无: 4, 自尊: 3, 热忱: 3 },
      },
      {
        text: '按住胸口：看清是怕，还是真有人拆台',
        flash: {
          who: '戈利亚德金',
          characterId: 'golyadkin-senior',
          line: '他按住胸口，强迫自己看清：拆台的也许不是别人，是怕。',
          image: '/assets/scenes/q08-C.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 5, 怜悯: 2, 激情: 2, 虚无: 2, 自尊: 3, 热忱: 2 },
      },
    ],
    quote: '最怕的不是对手，是那个更会处事的自己。',
    quoteSource: '《双重人格》',
  },
  {
    id: 'q09',
    scene: '桌上搁着入场券。屋里还在讲更高的和谐——你的手往哪放？',
    bookHint: '《卡拉马佐夫兄弟》',
    options: [
      {
        text: '推开椅子离场：眼泪比解释重',
        flash: {
          who: '伊万',
          characterId: 'ivan-karamazov',
          line: '他推开椅子，指着桌上的入场券：眼泪比你们的和谐重。',
          image: '/assets/scenes/q09-A.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 5, 怜悯: 4, 激情: 1, 虚无: 3, 自尊: 4, 热忱: 1 },
      },
      {
        text: '站起来，去找还在哭的人',
        flash: {
          who: '阿辽沙',
          characterId: 'alyosha-karamazov',
          line: '他没有赢下辩论。他只是站起来，去找那个还在哭的人。',
          image: '/assets/scenes/q09-B.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 2, 怜悯: 5, 激情: 1, 虚无: 1, 自尊: 2, 热忱: 5 },
      },
      {
        text: '听完高论，把刺默默记进心里',
        flash: {
          who: '斯麦尔佳科夫',
          characterId: 'smerdyakov',
          line: '他听完高论，嘴角几不可察地动了动：说归说，刺归刺。',
          image: '/assets/scenes/q09-C.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 3, 怜悯: 1, 激情: 2, 虚无: 5, 自尊: 3, 热忱: 1 },
      },
    ],
    quote: '我不是不接受上帝，我只是恭恭敬敬地把入场券退还。',
    quoteSource: '《卡拉马佐夫兄弟》',
  },
  {
    id: 'q10',
    scene: '你清醒知道对方空心。可一见面，狠话又碎掉——你？',
    bookHint: '《被侮辱与被损害的》',
    options: [
      {
        text: '亲手斩断，哪怕痛彻心扉',
        flash: {
          who: '杜尼娅',
          characterId: 'dunya',
          line: '她抬起下巴，把还想伸出的手收回：清醒地爱空心人，是对自己的背叛。',
          image: '/assets/scenes/q10-A.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 5, 怜悯: 2, 激情: 2, 虚无: 1, 自尊: 5, 热忱: 2 },
      },
      {
        text: '继续燃烧，不拿值不值得衡量',
        flash: {
          who: '娜塔莎',
          characterId: 'natasha',
          line: '她把指控都听完，眼睛仍亮：你们可以判我傻，不能替我决定我爱谁。',
          image: '/assets/scenes/q10-B.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 1, 怜悯: 4, 激情: 5, 虚无: 1, 自尊: 2, 热忱: 4 },
      },
      {
        text: '想走，见他又全部崩塌',
        flash: {
          who: '涅莉',
          characterId: 'nelly',
          line: '她退半步又停住。恨自己软弱，却更恨那双让她停下的眼睛。',
          image: '/assets/scenes/q10-C.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 2, 怜悯: 3, 激情: 4, 虚无: 3, 自尊: 4, 热忱: 2 },
      },
    ],
    quote: '我明知他是个空心人，我还是爱他。',
    quoteSource: '《被侮辱与被损害的》',
  },
  {
    id: 'q11',
    scene: '轮盘台发热。手段正在吞掉你想守护的人——你还赌吗？',
    bookHint: '《赌徒》',
    options: [
      {
        text: '收手，回到最初想守护的身边',
        flash: {
          who: '索尼娅',
          characterId: 'sonya',
          line: '她按住对方的手：筹码可以输光，人不能再被筹码换走。',
          image: '/assets/scenes/q11-A.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 4, 怜悯: 5, 激情: 2, 虚无: 1, 自尊: 2, 热忱: 4 },
      },
      {
        text: '再赌一把，也许下一轮就自由',
        flash: {
          who: '德米特里',
          characterId: 'dmitry-karamazov',
          line: '他眼睛发亮，把最后一点理智推过桌沿：已经没有回头路了。',
          image: '/assets/scenes/q11-B.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 1, 怜悯: 1, 激情: 5, 虚无: 3, 自尊: 3, 热忱: 4 },
      },
      {
        text: '分不清：为她，还是为那种心跳',
        flash: {
          who: '地下室人',
          characterId: 'underground-man',
          line: '他盯着旋转的红黑格：我已麻木，不知是爱她，还是爱心跳本身。',
          image: '/assets/scenes/q11-C.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 3, 怜悯: 2, 激情: 4, 虚无: 5, 自尊: 2, 热忱: 1 },
      },
    ],
    quote: '赢来的自由，有时比输更彻底地吞掉人。',
    quoteSource: '《赌徒》',
  },
  {
    id: 'q12',
    scene: '幸福终于敲门。你竟怕它太美、怕自己不配——你？',
    bookHint: '《脆弱的心》',
    options: [
      {
        text: '接住它，哪怕手还在抖',
        flash: {
          who: '娜斯简卡',
          characterId: 'nastenka',
          line: '她把门拉开一条缝：配不配从来不是问题——先让光进来。',
          image: '/assets/scenes/q12-A.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 2, 怜悯: 3, 激情: 3, 虚无: 1, 自尊: 2, 热忱: 5 },
      },
      {
        text: '推开试探，看它是否还回来',
        flash: {
          who: '阿格拉娅',
          characterId: 'aglaya',
          line: '她抬眼像在考试：你若经不起我推开，就别谈可靠。',
          image: '/assets/scenes/q12-B.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 4, 怜悯: 1, 激情: 3, 虚无: 2, 自尊: 5, 热忱: 2 },
      },
      {
        text: '在「何时失去」里耗干感受力',
        flash: {
          who: '阿尔卡季',
          characterId: 'arkady',
          line: '幸福还在门口，他已在心里把它失去一千次——手却不敢伸。',
          image: '/assets/scenes/q12-C.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 3, 怜悯: 2, 激情: 2, 虚无: 4, 自尊: 5, 热忱: 1 },
      },
    ],
    quote: '有人害怕的不是不幸，而是自己配不上突然到来的幸福。',
    quoteSource: '《脆弱的心》',
  },
  {
    id: 'q13',
    scene: '笼门开了。外面大得发晕，你竟想缩回去——你？',
    bookHint: '《死屋手记》',
    options: [
      {
        text: '拥抱自由，害怕也往前',
        flash: {
          who: '阿列伊',
          characterId: 'alei',
          line: '他踏出第一步，声音很轻：缩回笼子只是暂时舒服，长远是更大的毁灭。',
          image: '/assets/scenes/q13-A.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 3, 怜悯: 3, 激情: 2, 虚无: 1, 自尊: 3, 热忱: 5 },
      },
      {
        text: '退回牢笼，求人告诉我该做什么',
        flash: {
          who: '斯维德里盖洛夫',
          characterId: 'svidrigailov',
          line: '他笑着退半步：外面太无边了。有人安排日子，至少不会失眠。',
          image: '/assets/scenes/q13-B.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 3, 怜悯: 1, 激情: 1, 虚无: 5, 自尊: 2, 热忱: 1 },
      },
      {
        text: '理智往前，身体每秒想逃回',
        flash: {
          who: '亚历山大·彼得罗维奇',
          characterId: 'alexander-petrovich',
          line: '他记下这种撕裂：知道自由好，却仍听见号子里那种稳定的铃响。',
          image: '/assets/scenes/q13-C.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 5, 怜悯: 2, 激情: 2, 虚无: 3, 自尊: 4, 热忱: 2 },
      },
    ],
    quote: '人可以习惯一切，哪怕是绞刑架。',
    quoteSource: '《死屋手记》',
  },
  {
    id: 'q14',
    scene: '最亲近的人伤过你。原谅、报复，或用宽容折磨——你选？',
    bookHint: '《永久的丈夫》',
    options: [
      {
        text: '彻底原谅，各自走开',
        flash: {
          who: '阿辽沙',
          characterId: 'alyosha-karamazov',
          line: '他松开拳头：纠缠只会让伤口更湿。放下，各自走路。',
          image: '/assets/scenes/q14-A.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 3, 怜悯: 5, 激情: 1, 虚无: 1, 自尊: 2, 热忱: 4 },
      },
      {
        text: '暗中报复，让他也尝尝滋味',
        flash: {
          who: '罗戈任',
          characterId: 'rogozhin',
          line: '他的手指在桌沿捏白：表面宽容是虚伪的——我会等一个时机。',
          image: '/assets/scenes/q14-B.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 2, 怜悯: 1, 激情: 5, 虚无: 3, 自尊: 4, 热忱: 2 },
      },
      {
        text: '用「原谅」当武器，让他永背愧疚',
        flash: {
          who: '斯维德里盖洛夫',
          characterId: 'svidrigailov',
          line: '他温和地拍拍对方肩膀：我不报复。我的宽容，会比刀子更久。',
          image: '/assets/scenes/q14-C.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 5, 怜悯: 1, 激情: 2, 虚无: 5, 自尊: 4, 热忱: 1 },
      },
    ],
    quote: '最毒的宽恕，是让对方永远活在你的慈悲里。',
    quoteSource: '《永久的丈夫》',
  },
  {
    id: 'q15',
    scene: '门缝里有神秘气味。你知会被吞噬，却更想靠近——你？',
    bookHint: '《女房东》',
    options: [
      {
        text: '飞蛾扑火，危险本身就是燃料',
        flash: {
          who: '罗戈任',
          characterId: 'rogozhin',
          line: '他低声说：你是我的——不然谁都别想要。火焰比安全更像活着。',
          image: '/assets/scenes/q15-A.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 1, 怜悯: 1, 激情: 5, 虚无: 3, 自尊: 3, 热忱: 3 },
      },
      {
        text: '保持距离，真正的爱不该毁灭人',
        flash: {
          who: '杜尼娅',
          characterId: 'dunya',
          line: '她关上门，脊背仍发烫：被吞噬不是爱，是投降。',
          image: '/assets/scenes/q15-B.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 5, 怜悯: 2, 激情: 2, 虚无: 1, 自尊: 5, 热忱: 2 },
      },
      {
        text: '越痛越往前，分不清算不算爱',
        flash: {
          who: '涅托奇卡',
          characterId: 'netochka',
          line: '她抓住身边的人不放——像抓住自己还能被爱的证据，哪怕手被烫红。',
          image: '/assets/scenes/q15-C.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 1, 怜悯: 4, 激情: 5, 虚无: 2, 自尊: 3, 热忱: 2 },
      },
    ],
    quote: '有人从自我折磨里，辨认出一种病态的乐趣。',
    quoteSource: '《女房东》',
  },
  {
    id: 'q16',
    scene: '对方哭着求你别再对她好。你的付出，已是自己活着的证据——你？',
    bookHint: '《穷人》',
    options: [
      {
        text: '停止付出，先把自己捡回来',
        flash: {
          who: '瓦尔瓦拉',
          characterId: 'varvara-dobroselova',
          line: '她回信写得很清：若善意让彼此耗尽，那就该停——路要自己走。',
          image: '/assets/scenes/q16-A.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 5, 怜悯: 3, 激情: 2, 虚无: 1, 自尊: 5, 热忱: 3 },
      },
      {
        text: '继续付出，停下来等于让我死去',
        flash: {
          who: '杰武什金',
          characterId: 'makar-devushkin',
          line: '他搓着手改掉诉苦：不要剥夺我唯一活着的意义——就是照顾你。',
          image: '/assets/scenes/q16-B.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 1, 怜悯: 5, 激情: 2, 虚无: 1, 自尊: 3, 热忱: 5 },
      },
      {
        text: '想停，自我却已全系在他身上',
        flash: {
          who: '杰武什金',
          characterId: 'makar-devushkin',
          line: '笔停在纸上发抖。停下来，他就什么都没有了——包括自己。',
          image: '/assets/scenes/q16-C.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 2, 怜悯: 4, 激情: 3, 虚无: 3, 自尊: 4, 热忱: 2 },
      },
    ],
    quote: '不要剥夺我唯一活下去的意义——就是照顾你。',
    quoteSource: '《穷人》',
  },
  {
    id: 'q17',
    scene: '你按「为你好」去救一个人。对方越沉默，你越用力——你？',
    bookHint: '《温顺的女性》',
    options: [
      {
        text: '停下来听：我的帮助里可有傲慢',
        flash: {
          who: '阿辽沙',
          characterId: 'alyosha-karamazov',
          line: '他放下说教的手：也许我从未问过——你到底想要什么。',
          image: '/assets/scenes/q17-A.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 4, 怜悯: 5, 激情: 1, 虚无: 1, 自尊: 2, 热忱: 4 },
      },
      {
        text: '寒心抽身：有些人扶不上墙',
        flash: {
          who: '叶菲莫夫',
          characterId: 'yefimov',
          line: '他昂着头退开：我付出那么多，换来冷漠——那就烂在原地吧。',
          image: '/assets/scenes/q17-B.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 3, 怜悯: 1, 激情: 2, 虚无: 4, 自尊: 5, 热忱: 1 },
      },
      {
        text: '越抗拒越救，不知何时该停',
        flash: {
          who: '梅什金',
          characterId: 'prince-myshkin',
          line: '他红着脸仍往前伸手：我确实想帮你——可你退一步，我跟两步。',
          image: '/assets/scenes/q17-C.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 1, 怜悯: 5, 激情: 3, 虚无: 1, 自尊: 1, 热忱: 5 },
      },
    ],
    quote: '我是带着拯救她的意图娶她的。',
    quoteSource: '《温顺的女性》',
  },
  {
    id: 'q18',
    scene: '一个理念握着你走路。你渐渐分不清：是你在用它，还是它在用你？',
    bookHint: '跨书',
    options: [
      {
        text: '停下来审视：别让工具变成牢笼',
        flash: {
          who: '波尔菲里',
          characterId: 'porfiry',
          line: '他把椅子拉近一点：理念若让你失去选择，它就不再是你的刀。',
          image: '/assets/scenes/q18-A.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 5, 怜悯: 3, 激情: 1, 虚无: 2, 自尊: 3, 热忱: 3 },
      },
      {
        text: '继续被推着走，停即否定过去',
        flash: {
          who: '拉斯柯尔尼科夫',
          characterId: 'raskolnikov',
          line: '他握紧那想法，像握紧自己：它已经定义了我——停下等于否定全部。',
          image: '/assets/scenes/q18-B.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 4, 怜悯: 1, 激情: 4, 虚无: 3, 自尊: 5, 热忱: 4 },
      },
      {
        text: '分不清谁在思考，谁在被思考',
        flash: {
          who: '斯塔夫罗金',
          characterId: 'stavrogin',
          line: '众人把理想堆到他脚边。他只微微点头——不知是他站着，还是思想站着。',
          image: '/assets/scenes/q18-C.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 5, 怜悯: 1, 激情: 1, 虚无: 5, 自尊: 3, 热忱: 1 },
      },
    ],
    quote: '思想有自己活生生的命运，它使人疯狂，把人逼向极端。',
    quoteSource: '跨书',
  },
  {
    id: 'q19',
    scene: '桥栏冰凉，天边已白：这段相遇要散——你？',
    bookHint: '《白夜》',
    options: [
      {
        text: '全力投入，明知会散也要',
        flash: {
          who: '白夜梦想家',
          characterId: 'dreamer',
          line: '桥栏很凉。他把整个夏天的幻想，都押进这几个短短的夜晚。',
          image: '/assets/scenes/q19-A.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 1, 怜悯: 3, 激情: 4, 虚无: 1, 自尊: 1, 热忱: 3 },
      },
      {
        text: '说清去向，不把人留在幻象里',
        flash: {
          who: '娜斯简卡',
          characterId: 'nastenka',
          line: '她握住对方的手：谢谢你来过，我仍要往自己的光走。',
          image: '/assets/scenes/q19-B.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 4, 怜悯: 4, 激情: 3, 虚无: 1, 自尊: 3, 热忱: 3 },
      },
      {
        text: '珍视这一夜，不要求它成为一生',
        flash: {
          who: '娜斯简卡',
          characterId: 'nastenka',
          line: '她把故事讲完，声音轻而清楚：美可以短，诚实必须长。',
          image: '/assets/scenes/q19-C.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 4, 怜悯: 4, 激情: 2, 虚无: 2, 自尊: 3, 热忱: 2 },
      },
    ],
    quote: '我是个幻想家。我自己编造完整的生活。',
    quoteSource: '《白夜》',
  },
  {
    id: 'q20',
    scene: '车站灯光刺眼。一边是濒临毁灭的人，一边是爱你的人——你？',
    bookHint: '《白痴》',
    options: [
      {
        text: '走向苦难那边，哪怕伤了爱你的人',
        flash: {
          who: '梅什金',
          characterId: 'prince-myshkin',
          line: '车站的灯光很白。他走向那个被所有人议论的人，只说：我相信你。',
          image: '/assets/scenes/q20-A.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 1, 怜悯: 5, 激情: 1, 虚无: 1, 自尊: 1, 热忱: 4 },
      },
      {
        text: '抓住属于自己的爱，不再去拯救',
        flash: {
          who: '阿格拉娅',
          characterId: 'aglaya',
          line: '她抬眼看人，像在考试：你可以谈拯救，先证明你敢选我。',
          image: '/assets/scenes/q20-B.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 3, 怜悯: 2, 激情: 4, 虚无: 1, 自尊: 5, 热忱: 3 },
      },
      {
        text: '停在中间，任何选择都会伤人',
        flash: {
          who: '纳斯塔霞',
          characterId: 'nastasya',
          line: '她笑了一下，笑声里有刀：别用美来救我——你根本选不了。',
          image: '/assets/scenes/q20-C.jpg',
          imageKind: 'scene',
        },
        axes: { 理性: 2, 怜悯: 2, 激情: 4, 虚无: 4, 自尊: 4, 热忱: 1 },
      },
    ],
    quote: '美将拯救世界。',
    quoteSource: '《白痴》',
  },
]
